# Generated by Django 3.1.5 on 2021-07-20 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mould',
            fields=[
                ('mould_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mould_name', models.CharField(max_length=200)),
                ('cavity_number', models.IntegerField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('threshold_value', models.IntegerField()),
                ('present_count', models.IntegerField()),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
