# Generated by Django 3.1.5 on 2021-07-21 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mould', '0002_mouldstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouldComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('commented_date_time', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_user', to=settings.AUTH_USER_MODEL)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mould_chat', to='mould.mould')),
            ],
        ),
    ]
